name: Publish Docs

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing packages
        working-directory: ./.docs
        run: npm install

      - name: Build Nuxt 3 static site
        working-directory: ./.docs
        run: npx nuxi generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.docs/dist
          commit_message: 'Automatic deploy: ${{ github.event.head_commit.message }}'
